---
efi:
    mountPoint: "/boot"
    recommendedSize: 1GiB
    minimumSize: 512MiB
    label: "EFI"

userSwapChoices:
    - none
    - small
    - file

luksGeneration: luks2
enableLuksAutomatedPartitioning: true
preCheckEncryption: false
showNotEncryptedBootMessage: true

drawNestedPartitions: true
allowManualPartitioning: true
initialPartitioningChoice: none
initialSwapChoice: file
defaultPartitionTableType: gpt
requiredPartitionTableType: gpt
defaultFileSystemType: ext4
availableFileSystemTypes: [ ext4, btrfs ]

lvm:
    enable: true

essentialMounts: [ "live-*", "control", "ventoy" ]
