---
dontChroot: false
timeout: 600
verbose: true

i18n:
  name: "Configuring bootloader"
  name[ru]: "Настройка загрузчика"

script:
  - command: >-
      /usr/local/sbin/nyx-configure-bootloader "${gs[packagechooser_bootloader]}"
    timeout: 600
    verbose: true
