---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - audio
    - name: wheel
      must_exist: false
      system: true

sudoersGroup: wheel
sudoersConfigureWithGroup: false
setRootPassword: false
doReusePassword: false
displayAutologin: false
doAutologin: false

passwordRequirements:
    minLength: 8
    maxLength: 128
    libpwquality:
        - minlen=8
        - minclass=2

allowWeakPasswords: false
allowWeakPasswordsDefault: false

user:
    shell: /bin/bash
    forbidden_names: [ root, nobody ]
    home_permissions: "o755"

hostname:
    location: EtcFile
    writeHostsFile: true
    template: "nyxlinux"
    forbidden_names: [ localhost ]
