---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
showDonateUrl: false

requirements:
  requiredStorage: 20
  requiredRam: 4
  internetCheckUrl:
    - "https://archlinux.org"
    - "https://mirror.cachyos.org"
  check:
    - storage
    - ram
    - internet
  required:
    - storage
    - ram
    - internet

geoip:
  style: "none"
  url: "https://geoip.kde.org/v1/ubiquity"
  selector: "CountryCode"
