---
modules-search: [ local ]

instances:
  - id: desktop
    module: packagechooser
    config: packagechooser-desktop.conf
  - id: aurhelper
    module: packagechooser
    config: packagechooser-aurhelper.conf
  - id: bootloader
    module: packagechooser
    config: packagechooser-bootloader.conf
  - id: initramfs
    module: shellprocess
    config: shellprocess-initramfs.conf
    weight: 30
  - id: bootloader-config
    module: shellprocess
    config: shellprocess-bootloader.conf
    weight: 30

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - packagechooser@desktop
      - packagechooser@aurhelper
      - packagechooser@bootloader
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - machineid
      - unpackfs
      - users
      - locale
      - keyboard
      - localecfg
      - fstab
      - packages
      - initcpiocfg
      - shellprocess@initramfs
      - displaymanager
      - services-systemd
      - grubcfg
      - shellprocess@bootloader-config
      - umount
  - show:
      - finished

branding: archlinux
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
